apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-label
  template:
    metadata:
      labels:
        app: nodeapp-label
        demo: demo-label
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: auth
      containers:
        - name: nodeapp-container
          image: "{{ACR}}.azurecr.io/nodeapp:latest"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    demo: demo-label
spec:
  type: LoadBalancer
  selector:
    app: nodeapp-label
  ports:
    - port: 80
      targetPort: 3000
      name: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurefunc-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurefunc-app-label
  template:
    metadata:
      labels:
        app: azurefunc-app-label
        demo: demo-label
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: auth
      containers:
        - name: azurefunc-app-container
          image: "{{ACR}}.azurecr.io/azurefunctionsapp:latest"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: serverlessapp
  labels:
    demo: demo-label
spec:
  type: ClusterIP
  selector:
    app: azurefunc-app-label
  ports:
    - port: 80
      targetPort: 80
      name: serverlessapp
