apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: monitoring
  labels:
    app: servicemonitor-label
    prometheus: kube-prometheus
    demo: demo-label
spec:
  selector:
    matchLabels:
      demo: demo-label
  jobLabel: demo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: web
